services:
  - type: cron
    name: schwalbe-price-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    schedule: "0 */6 * * *"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
